services:
  markernav:
    image: markernav:x86
    # image: markernav:arm
    build: .
#    network_mode: host
    volumes:
      - .:/markernav
    cap_add:
      - NET_ADMIN
    # networks:
    #   - my_bridge

networks:
  my_bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.200.0/24
          ip_range: 192.168.200.232/32
          gateway: 192.168.200.1
#          aux_addresses:
#            markernav: 192.168.200.234