(cl:in-package test_get_image-msg)
(cl:export '(UTCTIME-VAL
          UTCTIME
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          ALTITUDE-VAL
          ALTITUDE
          HEADING-VAL
          HEADING
          PROPERTYTYPE-VAL
          PROPERTYTYPE
          MEASURE-VAL
          MEASURE
          FEATURE-VAL
          FEATURE
          PROCESS-VAL
          PROCESS
          PARAMETER-VAL
          PARAMETER
          RESULTQUALITY-VAL
          RESULTQUALITY
          ORCHARDID-VAL
          ORCHARDID
          CAMERAID-VAL
          CAMERAID
          SECONDARYCAMERAID-VAL
          SECONDARYCAMERAID
          IMAGEID-VAL
          IMAGEID
          SECONDARYIMAGEID-VAL
          SECONDARYIMAGEID
          INSLATITUDE-VAL
          INSLATITUDE
          INSLONGITUDE-VAL
          INSLONGITUDE
          INSALTITUDE-VAL
          INSALTITUDE
          INSTIME-VAL
          INSTIME
))