float64             utcTime
float64             latitude
float64             longitude
float64             altitude
float64             heading

std_msgs/String     propertyType
float64             measure

std_msgs/String     feature
std_msgs/String     process
std_msgs/String     parameter
std_msgs/String     resultQuality

std_msgs/String     OrchardID
std_msgs/String     CameraID
std_msgs/String     SecondaryCameraID
std_msgs/String     ImageID
std_msgs/String     SecondaryImageID

float64             INSlatitude
float64             INSlongitude
float64             INSaltitude
float64             INStime
